name: Build

on:
  - push
  - pull_request

permissions:
  packages: read # Allow downloading of packages.

jobs:
  build:
    name: Build
    runs-on: ubuntu-slim
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Prepare
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6

      - name: Setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          registry-url: https://npm.pkg.github.com
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install
        run: |
          pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          pnpm run lint
