name: Renovate

on:
  schedule:
    - cron: "9/15 * * * *"

permissions:
  packages: read # Allow downloading of packages.

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      NPM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Renovate
        uses: renovatebot/github-action@eaf12548c13069dcc28bb75c4ee4610cdbe400c5 # v44.2.6
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.config.cjs
        env:
          LOG_LEVEL: info
          RENOVATE_GIT_AUTHOR_NAME: ${{ secrets.RENOVATE_GIT_AUTHOR_NAME }}
          RENOVATE_GIT_AUTHOR_EMAIL: ${{ secrets.RENOVATE_GIT_AUTHOR_EMAIL }}
          RENOVATE_GITHUB_PACKAGE_TOKEN: ${{ secrets.RENOVATE_GITHUB_PACKAGE_TOKEN }}
